[build]
builder = "nixpacks"
buildCommand = "apk add --no-cache git && go mod download && GOOS=linux GOARCH=amd64 go build -o main ./cmd/api"

[deploy]
startCommand = "./main"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 