[build]
builder = "nixpacks"
buildCommand = "go mod download && GOOS=linux GOARCH=amd64 go build -o main ./cmd/api"

[deploy]
startCommand = "./main"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 